name: "Notify Teams"
description: "Send Microsoft Teams notification with status"
inputs:
  status:
    required: true
  commit:
    required: true
  sonar_url:
    required: true
  teams_webhook:
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        STATUS="${{ inputs.status }}"
        COMMIT="${{ inputs.commit }}"
        COMMIT_SHORT=$(echo "$COMMIT" | cut -c1-7)
        SONAR_URL="${{ inputs.sonar_url }}"
        TEAMS_WEBHOOK="${{ inputs.teams_webhook }}"
        WORKFLOW="${{ github.workflow }}"
        REPOSITORY="${{ github.repository }}"
        REF="${{ github.ref }}"
        SERVER_URL="${{ github.server_url }}"

        if [ "$STATUS" = "success" ]; then
          COLOR="00FF00"
          MESSAGE="✅ FFB Webservices - Sonar Succeeded"
          IMAGE_URL="https://c.tenor.com/Ud36Rrav628AAAAC/tenor.gif"
        else
          COLOR="FF0000"
          MESSAGE="❌ FFB Webservices - Sonar Failed"
          IMAGE_URL="https://c.tenor.com/nsEfkzN30TIAAAAC/tenor.gif"
        fi

        PAYLOAD=$(cat <<EOF
        {
          "@type": "MessageCard",
          "@context": "http://schema.org/extensions",
          "summary": "$MESSAGE",
          "themeColor": "$COLOR",
          "title": "$MESSAGE",
          "sections": [{
            "text": "**Workflow**: $WORKFLOW  \n**Repository**: $REPOSITORY  \n**Branch**: $REF  \n**Commit**: [$COMMIT_SHORT]($SERVER_URL/$REPOSITORY/commit/$COMMIT)  \n**SonarQube Analysis**: [View Results]($SONAR_URL)",
            "images": [{
              "image": "$IMAGE_URL"
            }],
            "markdown": true
          }]
        }
        EOF
        )

        curl -H "Content-Type: application/json" -d "$PAYLOAD" "$TEAMS_WEBHOOK"
      shell: bash
