name: "fanfictionsbookmarks"

services:
  mysql:
    image: mysql:latest
    container_name: mysql_ffb
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: fhurai
      MYSQL_PASSWORD: 77/ffb*Usager
    ports:
      - "7706:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - ffb_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_ffb
    restart: always
    environment:
      PMA_HOST: mysql_ffb
      PMA_PASSWORD: root
    ports:
      - "7703:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ffb_network

  nginx:
    image: nginx:latest
    container_name: nginx_ffb
    ports:
      - "7780:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - .:/var/www/html
      - ./nginx:/etc/nginx/conf.d
      - ./scripts/nginx-entrypoint.sh:/docker-entrypoint.d/nginx-entrypoint.sh
    depends_on:
      - php
    networks:
      - ffb_network

  php:
    image: fhurai/api_ffb:latest
    container_name: php_ffb
    healthcheck:
      test: ["CMD", "php", "-v"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - DB_HOST=mysql_ffb
      - PHP_HOST=nginx_ffb
    networks:
      - ffb_network

volumes:
  mysql_data:

networks:
  ffb_network:
    driver: bridge
