<?php

declare(strict_types=1);

use PHPUnit\Framework\Attributes\DataProvider;

require_once __DIR__ . '/../../tests/api/ApiTestCase.php';

#[\PHPUnit\Framework\Attributes\CoversClass(\ApiClient::class)]
#[\PHPUnit\Framework\Attributes\CoversClass(className: \Character::class)]
class CharactersTest extends ApiTestCase
{
    #[DataProvider('characterNamesProvider')]
    public function testCharacterNames(string $expectedName, int $index): void
    {
        $characters = $this->fetchData('/characters.php');

        $this->assertArrayHasKey($index, $characters, "Character type at index {$index} is missing");
        $this->assertEquals($expectedName, $characters[$index]->name, "Character type name at index {$index} does not match");
    }

    public function testCharactersCount(): void
    {
        $characters = $this->fetchData('/characters.php');
        $this->assertCount(
            count(self::characterNamesProvider()),
            $characters,
            'The number of characters returned does not match the expected count'
        );
    }

    public static function characterNamesProvider(): array
    {
        return [
            ["Angelise Ikaruga Misurugi",0],
            ["Hilda Schlievogt",1],
            ["Salamandinay",2],
            ["Salia Tereshkova",3],
            ["Tusk",4],
            ["Momoka Oginome",5],
            ["OC",6],
            ["Cloud Strife",7],
            ["Tifa Lockheart",8],
            ["Barret Wallace",9],
            ["Aerith Gainsborough",10],
            ["Nanaki | Red XIII",11],
            ["Yuffie Kisaragi",12],
            ["Vincent Valentine",13],
            ["Cid Highwind",14],
            ["Biggs",15],
            ["Wedge",16],
            ["Jessie",17],
            ["Marlene Wallace",18],
            ["Denzel",19],
            ["Zack Fair",20],
            ["Zangan",21],
            ["Yuna",22],
            ["Tidus",23],
            ["Wakka",24],
            ["Lulu",25],
            ["Kimahri Ronso",26],
            ["Auron",27],
            ["Rikku",28],
            ["OC",29],
            ["OFC",30],
            ["Minfilia Warde",31],
            ["Y'shtola Rhul",32],
            ["Y'mhitra Rhul",33],
            ["Harry Potter",34],
            ["Hermione Granger",35],
            ["Ronald 'Ron' Weasley",36],
            ["Ginevra 'Ginny' Weasley",37],
            ["Daphne Greengrass",38],
            ["Fleur Delacour",39],
            ["Gabrielle Delacour",40],
            ["Pansy Parkinson",41],
            ["Luna Lovegood",42],
            ["Alicia Spinnet",43],
            ["William 'Bill' Weasley",44],
            ["Edward 'Teddy' Lupin",45],
            ["Perceval 'Percy' Weasley",46],
            ["Scorpius Malfoy",47],
            ["Albus Severus Potter",48],
            ["James Sirius Potter",49],
            ["Lily Luna Potter",50],
            ["Rose Weasley",51],
            ["Hugo Weasley",52],
            ["Victoire Weasley",53],
            ["Dominique Weasley",54],
            ["Louis Weasley",55],
            ["Molly II Weasley",56],
            ["Lucy Weasley",57],
            ["Roxanne Weasley",58],
            ["Frederick II Weasley",59],
            ["Nymphadora Tonks",60],
            ["Neville Longbottom",61],
            ["Dean Thomas",62],
            ["Seamus Finnigan",63],
            ["James Potter",64],
            ["Sirius Black",65],
            ["Lily Evans Potter",66],
            ["Remus Lupin",67],
            ["Peter Pettigrow",68],
            ["Draco Malfoy",69],
            ["Angelina Johnson",70],
            ["Katie Bell",71],
            ["Frederick 'Fred' Weasley",72],
            ["George Weasley",73],
            ["Oliver Wood",74],
            ["Lavender Brown",75],
            ["Parvati Patil",76],
            ["Padma Patil",77],
            ["Terry Boot",78],
            ["Kingsley Shacklebolt",79],
            ["Charles 'Charlie' Weasley",80],
            ["Blaise Zabini",81],
            ["Rita Skeeter",82],
            ["Gawain Robards",83],
            ["Milicent Bulstrode",84],
            ["Hannah Abbott",85],
            ["Susan Bones",86],
            ["Romilda Vane",87],
            ["Lee Jordan",88],
            ["Narcissa Black Malfoy",89],
            ["Tom Marvolo Riddle | Voldemort",90],
            ["Lucius Malfoy",91],
            ["Rodolphus Lestrange",92],
            ["Rabastan Lestrange",93],
            ["Bellatrix Black Lestrange",94],
            ["Alecto Carrow",95],
            ["Amycus Carrow",96],
            ["Andromeda Black Tonks",97],
            ["Cho Chang",98],
            ["Cedric Diggory",99],
            ["Viktor Krum",100],
            ["Cormac McLaggen",101],
            ["Astoria Greengrass",102],
            ["Theodore Nott",103],
            ["Tracey Davis",104],
            ["Arthur Weasley",105],
            ["Molly Weasley",106],
            ["Augusta Longbottom",107],
            ["Severus Snape",108],
            ["Ernie McMillan",109],
            ["Madam Hooch",110],
            ["Albus Dumbledore",111],
            ["Gellert Grindelwald",112],
            ["Minerva McGonagall",113],
            ["Filius Flitwick",114],
            ["Amelia Bones",115],
            ["Madam Rosmerta",116],
            ["Moaning Myrtle",117],
            ["Vernon Dursley",118],
            ["Petunia Evans Dursley",119],
            ["Dudley Dursley",120],
            ["John Dawlish",121],
            ["Delores Umbridge",122],
            ["Hestia Jones",123],
            ["Rubeus Hagrid",124],
            ["Griphook",125],
            ["Dobby",126],
            ["Kreacher",127],
            ["Winky",128],
            ["Cornelius Fudge",129],
            ["Poppy Pomfrey",130],
            ["Fawkes",131],
            ["Barnabus Cuffe",132],
            ["Pomona Sprout",133],
            ["Sybill Trelawney",134],
            ["Marcus Flint",135],
            ["Gilderoy Lockhart",136],
            ["Quirinus Quirell",137],
            ["Alastor 'Mad-Eye' Moody",138],
            ["Rufus Scrimgeour",139],
            ["Arabella Figg",140],
            ["Bartemius Crouch Sr.",141],
            ["Bartemius Crouch Jr.",142],
            ["Garrick Ollivander",143],
            ["OMC",144],
            ["OFC",145],
            ["Millicent Bulstrode",146],
            ["Apolline Delacour",147],
            ["Flora Carrow",148],
            ["Gregory Goyle",149],
            ["Amos Diggory",150],
            ["Buckbeak",151],
            ["Su Li",152],
            ["Hestia Carrow",153],
            ["Gwenog Jones",154],
            ["Newt Scamander",155],
            ["Rolf Scamander",156],
            ["Penelope Clearwater",157],
            ["Kevin Entwhistle",158],
            ["Marlene McKinnon",159],
            ["Demelza Robins",160],
            ["Edward 'Ted' Tonks",161],
            ["Adrian Pucey",162],
            ["Salazar Slytherin",163],
            ["Fay Dunbar",164],
            ["Cassiopeia Black",165],
            ["Marietta Edgecomb",166],
            ["Integra Hellsing",167],
            ["Alucard",168],
            ["Seras Victoria",169],
            ["Walter C. Dornez",170],
            ["Shepard (F)",171],
            ["Shepard (M)",172],
            ["Liara T'Soni",173],
            ["Garrus Vakarian",174],
            ["Ashley Williams",175],
            ["Kaidan Alenko",176],
            ["Tali'Zorah",177],
            ["Urdnot Wrex",178],
            ["David Anderson",179],
            ["Nihlus Kryik",180],
            ["Saren Arterius",181],
            ["Desolas Arterius",182],
            ["Steven Hackett",183],
            ["Shiala",184],
            ["Benezia T'Soni",185],
            ["Councilor Tevos",186],
            ["Councilor Sparatus",187],
            ["Councilor Valern",188],
            ["Miranda Lawson",189],
            ["Jacob Taylor",190],
            ["Mordin Solus",191],
            ["Jack",192],
            ["Urdnot Grunt",193],
            ["Kasumi Goto",194],
            ["Zaeed Massani",195],
            ["Thane Krios",196],
            ["Samara",197],
            ["Morinth",198],
            ["Legion",199],
            ["James Vega",200],
            ["EDI",201],
            ["Javik",202],
            ["Jeff 'Joker' Moreau",203],
            ["Charles Pressly",204],
            ["Karin Chakwas",205],
            ["Greg Adams",206],
            ["Jack Harper | The Illusive Man",207],
            ["Kai Leng",208],
            ["Aria T'Loak",209],
            ["Sovereign",210],
            ["Harbringer",211],
            ["Sha'ira",212],
            ["Maya Brooks",213],
            ["Matriarch Aethyta",214],
            ["Brynn Cole",215],
            ["Shadow Broker",216],
            ["Rachni Queen",217],
            ["Hannah Shepard",218],
            ["Scott Ryder",219],
            ["Sara Ryder",220],
            ["Pelessaria 'Peebee' B’Sayle",221],
            ["Jaal Ama Darav",222],
            ["Chigusa Nana",223],
            ["Sugimura Kaoru",224],
            ["Tachibana Mitsuko",225],
            ["Tachi Ryoko",226],
            ["Sarashina Shuutarou",227],
            ["Uzumaki Naruto",228],
            ["Umino Iruka",229],
            ["Haruno Sakura",230],
            ["Uchiwa Sasuke",231],
            ["Hyuuga Hinata",232],
            ["Hatake Kakashi",233],
            ["Namikaze Minato",234],
            ["Uzumaki Kushina",235],
            ["Inuzuka Kiba",236],
            ["Aburame Shino",237],
            ["Sai",238],
            ["Yamanaka Ino",239],
            ["Nara Shikamaru",240],
            ["Akimichi Choji",241],
            ["Rock Lee",242],
            ["Hyuuga Neji",243],
            ["Tenten",244],
            ["Sabaku no Gaara",245],
            ["Sabaku no Kankuro",246],
            ["Sabaku no Temari",247],
            ["Sarutobi Hiruzen",248],
            ["Sarutobi Asuma",249],
            ["Sarutobi Konohamaru",250],
            ["Yuuhi Kurenai",251],
            ["Maito Gai",252],
            ["Ebisu",253],
            ["Orochimaru",254],
            ["Jiraya",255],
            ["Senju Tsunade",256],
            ["Shizune",257],
            ["Yuki Haku",258],
            ["Momochi Zabuza",259],
            ["Jirobo",260],
            ["Kidomarou",261],
            ["Sakon",262],
            ["Ukon",263],
            ["Tayuya",264],
            ["Kaguya Kimimaro",265],
            ["Yakushi Kabuto",266],
            ["Akasuna no Sasori",267],
            ["Deidara",268],
            ["Hidan",269],
            ["Kakuzu",270],
            ["Hoshigaki Kisame",271],
            ["Uchiwa Itachi",272],
            ["Karui",273],
            ["Samui",274],
            ["Omoi",275],
            ["Killer Bee",276],
            ["Tobi | Uchiwa Obito",277],
            ["Pein | Uzumaki Nagato",278],
            ["Konan",279],
            ["Yahiko",280],
            ["Zetsu",281],
            ["Uchiwa Madara",282],
            ["Senju Hashirama",283],
            ["Senju Tobirama",284],
            ["Ootsutsuki Hagoromo",285],
            ["Ootsutsuki Hamura",286],
            ["Ootsutsuki Ashura",287],
            ["Ootsutsuki Indra",288],
            ["Kyubi | Kurama",289],
            ["Hachibi | Gyuki",290],
            ["Nanabi | Chomei",291],
            ["Rokubi | Saiken",292],
            ["Gobi | Kokuo",293],
            ["Yonbi | Songoku",294],
            ["Sanbi | Isobu",295],
            ["Nibi | Matatabi",296],
            ["Ichibi | Shukaku",297],
            ["Mitarashi Anko",298],
            ["Uzumaki Naruko",299],
            ["Ko Hyuga",300],
            ["Hyuuga Hiashi",301],
            ["Hyuuga Hanabi",302],
            ["Hokuto",303],
            ["Kin Tsuchi",304],
            ["Natsuhi",305],
            ["Ootsutsuki Kaguya",306],
            ["OFC",307],
            ["Terumi Mei",308],
            ["Ginkaku",309],
            ["Kinkaku",310],
            ["Ootsutsuki Toneri",311],
            ["Fuka",312],
            ["Hotaru",313],
            ["Fuu",314],
            ["Amaru",315],
            ["Inuzuka Hana",316],
            ["Shizuka",317],
            ["Karin",318],
            ["Kazahana Koyuki | Fujikaze Yukie",319],
            ["Queen Sara",320],
            ["Uzumaki Boruto",321],
            ["Uzumaki Himawari",322],
            ["Yamato | Tenzou",323],
            ["Yamanaka Inojin",324],
            ["Uchiwa Sarada",325],
            ["Nara Shikadai",326],
            ["Akimichi Chouza",327],
            ["Nara Shikaku",328],
            ["Yamanaka Inoichi",329],
            ["Atsui",330],
            ["Mabui",331],
            ["Shiranui Genma",332],
            ["Inuzuka Tsume",333],
            ["Aburame Shibi",334],
            ["Shimura Danzo",335],
            ["Kurotsuchi",336],
            ["Kazamatsuri Moegi",337],
            ["Nara Yoshino",338],
            ["Haruno Kizashi",339],
            ["Haruno Mebuki",340],
            ["Uchiwa Mikoto",341],
            ["Uchiwa Fugaku",342],
            ["Shion",343],
            ["Nii Yugito",344],
            ["Matsuri",345],
            ["Akamaru",346],
            ["Tracer | Lena Oxton",347],
            ["Widowmaker | Amelie Lacroix",348],
            ["Taylor Hebert",349],
            ["James Raynor",350],
            ["Sarah Kerrigan",351],
            ["Artanis",352],
            ["Zeratul",353],
            ["Tassadar",354],
            ["Matt Horner",355],
            ["November 'Nova' Terra",356],
            ["Acturus Mengsk",357],
            ["Valerian Mengsk",358],
            ["Gerard Dugalle",359],
            ["Fenix",360],
            ["Raszagal",361],
            ["Tychus Findlay",362],
            ["Samir Duran",363],
            ["Magistrate",364],
            ["Geralt z Rivii | Geralt of Rivia",365],
            ["Yennefer z Vengerbergu | Yennefer of Vengerberg",366],
            ["Lambert",367],
            ["Cirilla Fiona Elen Riannon",368],
            ["Morvran Voorhis",369],
            ["Philippa Eilhart",370],
            ["Eskel",371],
            ["Vesemir",372],
            ["Jaskier | Dandelion",373],
            ["Zoltan Chivay",374],
            ["Emiel Regis Rohellec Terzieff-Godefroy",375],
            ["Keira Metz",376],
            ["Triss Merigold",377],
            ["Shulk",378],
            ["Reyn",379],
            ["Fiorung | Fiora",380],
            ["Carna | Sharla",381],
            ["Dunban",382],
            ["Riki",383],
            ["Melia Ancient | Melia Antiqua",384],
            ["Alvis",385],
            ["Zanza",386],
            ["Linada",387],
            ["Nene",388],
            ["Kino",389],
            ["Talco | Tyrea",390],
            ["Vanea",391],
            ["Egil",392],
            ["Miqol",393],
            ["Galatea | Galea",394],
            ["OFC",395],
            ["OMC",396],
            ["Ontos",397],
            ["Teto | Teelan",398],
            ["Nopon Archsage",399],
            ["Mir'liez",400],
            ["Emmy Leater",401],
            ["Rex",402],
            ["Metsu | Malos",403],
            ["Hikari | Mythra",404],
            ["Homura | Pyra",405],
            ["Seiryuu | Azurda",406],
            ["Shin | Jin",407],
            ["Niyah | Nia",408],
            ["Byakko | Dromarch",409],
            ["Meleph | Mòrag Ladair",410],
            ["Kagutsuchi | Brighid",411],
            ["Hana | Poppi",412],
            ["Tora",413],
            ["Yew",414],
            ["Zuo",415],
            ["Ozychlyrus Brounev Tantal | Zeke von Genbu",416],
            ["Saika | Pandoria",417],
            ["Aquila Paronet Sol Esteriole | Vandham",418],
            ["Marubeeni | Amalthus",419],
            ["Yoshitsune | Akhos",420],
            ["Benkei | Patroka",421],
            ["Satahiko | Mikhail",422],
            ["Klaus",423],
            ["Pneuma",424],
            ["Logos",425],
            ["Lora",426],
            ["Adel Orudou | Addam Origo",427],
            ["Minochi | Cole | Minoth",428],
            ["Nephel | Niall Ardanach",429],
            ["Wadatsumi | Aegaeon",430],
            ["Corrine",431],
            ["Shiki | Adenine",432],
            ["Newt",433],
            ["KOS-MOS",434],
            ["Hibana | Crossette",435],
            ["Suzaku | Roc",436],
            ["Zeerihhi | Eulogimenos",437],
            ["Mikumari | Praxis",438],
            ["Rageruto | Raqura",439],
            ["Kamekichi | Turters",440],
            ["Jikarao | Wulfric",441],
            ["Theory",442],
            ["Vasara | Perceval",443],
            ["Uka | Nim",444],
            ["Nanakoori | Ursula",445],
            ["Kubira | Dagas",446],
            ["Zantetsu | Sever",447],
            ["Mio",448],
            ["Noah",449],
            ["Eunie",450],
            ["Taion",451],
            ["Sena",452],
            ["Lanz",453],
            ["Kagiroi | Glimmer",454],
            ["Nikol",455],
            ["Alpha",456],
            ["A",457],
            ["Ghondor Vandham Sr.",458],
            ["Ghondor Vandham Jr.",459],
            ["Monica Vandham",460],
            ["Guernica Vandham",461],
            ["Matthew Vandham",462],
            ["M(io)",463],
            ["N(oah)",464],
            ["C(rys)",465],
            ["D(irk)",466],
            ["J(oran)",467],
            ["Ino",468],
            ["Masha",469],
            ["Ethel",470],
            ["Valdi",471],
            ["Zeon",472],
            ["Kite",473],
            ["Riku",474],
            ["Manana",475],
            ["Shidou | Teach",476],
            ["Gray",477],
            ["Niina | Alexandria",478],
            ["Isurugi | Isurd",479],
            ["Nami | Nimue",480],
            ["Yuzuriha | Juniper",481],
            ["Ashera",482],
            ["Mashiro | Fiona",483],
            ["T(riton)",484],
            ["Kamunabi | Cammuravi",485],
            ["No. 13",486],
            ["No. 7 | Nagiri | Segiri",487],
            ["X",488],
            ["Y",489],
            ["Z",490],
            ["Miyabi",491],
            ["Linka",492],
            ["Panacea",493],
            ["Geseru | Garvel",494],
            ["Crys",495],
            ["Bolearis",496],
            ["P",497],
            ["Joran",498],
            ["Kotori | Chickadee",499],
            ["Michiba",500],
            ["Rozana",501],
            ["Maybach",502],
            ["OFC",503],
            ["OMC",504],
            ["Georgie",505],
            ["Shania Reid",506],
            ["S(hania)",507]
        ];
    }
}
