<?php

declare(strict_types=1);

use PHPUnit\Framework\Attributes\DataProvider;

require_once __DIR__ . '/../../tests/api/ApiTestCase.php';

#[\PHPUnit\Framework\Attributes\CoversClass(\ApiClient::class)]
#[\PHPUnit\Framework\Attributes\CoversClass(className: \Fanfiction::class)]
class FanfictionsTest extends ApiTestCase
{
    #[DataProvider('fanfictionNamesProvider')]
    public function testFanfictionNames(string $expectedName, int $index): void
    {
        $fanfictions = $this->fetchData('/fanfictions.php');

        $this->assertArrayHasKey($index, $fanfictions, "Fanfiction type at index {$index} is missing");
        $this->assertEquals($expectedName, $fanfictions[$index]->name, "Fanfiction type name at index {$index} does not match");
    }

    public function testFanfictionsCount(): void
    {
        $fanfictions = $this->fetchData('/fanfictions.php');
        $this->assertCount(
            count(self::fanfictionNamesProvider()),
            $fanfictions,
            'The number of fanfictions returned does not match the expected count'
        );
    }

    public static function fanfictionNamesProvider(): array
    {
        return [
            ["Dancing Dragonflies",0],
            ["Necessary",1],
            ["Life in the New World",2],
            ["We'll not die!",3],
            ["Cross Ange: The Knight of Hilda",4],
            ["Waiting",5],
            ["The Lost Love Letters of Cloud Strife",6],
            ["The Comeback Kid",7],
            ["Innocent Feelings",8],
            ["Journey of a Barmaid",9],
            ["Emerald Dream",10],
            ["Golden Respite",11],
            ["Lost Heart",12],
            ["Fractured Mind",13],
            ["Starlight",14],
            ["Post Crisis",15],
            ["The Gunslinger",16],
            ["Final Fantasy: Guardians",17],
            ["Twist in Fate",18],
            ["Final Fantasy X: All Bets Are Off",19],
            ["All Bets Are Off: The Sequel",20],
            ["FFX: All Bets Are Off 3: Tidus & Yuna Forever",21],
            ["FFX: All Bets Are Off 4: For the Love of Tidus",22],
            ["All Bets Are Off V: The Conclusion",23],
            ["Neo-Genesis",24],
            ["Spira's Dream",25],
            ["Spira's Sphere",26],
            ["Spira's Revenge",27],
            ["The More the Merrier",28],
            ["Mixed Up Dreams",29],
            ["Lost in Muggle London",30],
            ["The Perils of Too Much Calming Potion",31],
            ["Second String",32],
            ["Family",33],
            ["No Rules",34],
            ["Muggle Relations",35],
            ["Family Time",36],
            ["Lucky Kids",37],
            ["Expanding Bed Charms",38],
            ["Not a Phase",39],
            ["Awkward Lunch",40],
            ["At the Hogsnock Baths",41],
            ["Perfect Gingerbread Men",42],
            ["Outsider",43],
            ["Greek Holiday",44],
            ["The Daily Prophet Is Still a Gossip Rag",45],
            ["Best and the Brightest",46],
            ["Fancy That",47],
            ["From One Good Time To Another",48],
            ["Grey Haven",49],
            ["The Red Dress",50],
            ["Up Against the Wall",51],
            ["Caught",52],
            ["Parkinson's Knickers (Or Lack Thereof)",53],
            ["Quid Pro Quo",54],
            ["Games Without Frontiers",55],
            ["All's Fair",56],
            ["Another Kind of Lesson",57],
            ["Another Kind of Teacher",58],
            ["Another Kind of Punishment",59],
            ["Walkies",60],
            ["You Did Say \"Anything\"",61],
            ["Playing Games",62],
            ["Just Ask",63],
            ["The Challenges of Remote Subbing",64],
            ["Pretty From Behind",65],
            ["Bliss",66],
            ["That'll Show Them",67],
            ["Normal",68],
            ["Horny at Hogwarts",69],
            ["Clueless",70],
            ["The Metamorph Bet",71],
            ["The Shagging Spot",72],
            ["The Encore",73],
            ["The Minister's Affair",74],
            ["Favours & Benefits",75],
            ["This Christmas",76],
            ["The Stockings Were Hung by the Chimney With Care",77],
            ["Stress Relief",78],
            ["A Very Happy Mother's Day",79],
            ["Property of Potter",80],
            ["The One Blessing of a Curse",81],
            ["Stress Relief",82],
            ["The Weasley Witches Collective",83],
            ["Bad Day (Or How to Get Hermione to Stop Worrying And Enjoy Sex While On The Clock)",84],
            ["First Times",85],
            ["Eros & Psyche",86],
            ["Birthday Wishes",87],
            ["I wasn't thinking about you, again.",88],
            ["Euphemism is a perfectly good word",89],
            ["That Need",90],
            ["Seekers of Love",91],
            ["I'm Sure!",92],
            ["Fly Away",93],
            ["Uninhibited: Nymphadora",94],
            ["Dominating Daphne",95],
            ["Daphne Dominates",96],
            ["Daytime Domination",97],
            ["Ginny's Need",98],
            ["The Bet",99],
            ["Sustenance.",100],
            ["Ginny's Appetite",101],
            ["Dinner, Date...Draco?",102],
            ["When the Magic Stops Working",103],
            ["Broom Cupboard Encounters",104],
            ["Harry Potter and his luscious Butt",105],
            ["The Hogwarts Renewal Program",106],
            ["Tit for Tat",107],
            ["A Vampire Legacy; the story",108],
            ["Saving the Savior",109],
            ["The Last Time",110],
            ["No Thank You",111],
            ["Rouse the Dead",112],
            ["Healing",113],
            ["Office Fun",114],
            ["Reward",115],
            ["\"Harry Potter and the Unbreakable Bond\"",116],
            ["I'm Worried About Harry",117],
            ["Before the Wedding",118],
            ["Roman Holiday",119],
            ["Goblin Warfare",120],
            ["Harry Potter and the Veela Sisters",121],
            ["Christmas Holiday",122],
            ["Quiet",123],
            ["Falling Through Clouds",124],
            ["Private Party in the Conservatory",125],
            ["Christmas Cheer",126],
            ["Slytherin Games (Remix of Snakes)",127],
            ["Anonymous Signs",128],
            ["my heart is holding on to you",129],
            ["Candy Cane Obsessed Freak",130],
            ["Female Transfiguration 101",131],
            ["Bedtime",132],
            ["Tea with the Headmistress",133],
            ["Fire",134],
            ["Accio Ballgag!",135],
            ["Christmas Bells are Ringing",136],
            ["For This One Day",137],
            ["A Birthday Gift",138],
            ["A Night in the Lioness' Den",139],
            ["Trouble, with a Capital T",140],
            ["They spurn the holiday spirit in their usual way",141],
            ["Birthday Surprise",142],
            ["Walking the Walk",143],
            ["Your secret fantasy",144],
            ["Change of Heart",145],
            ["Addictive",146],
            ["Restorative",147],
            ["Who Seems a Beast (but secretly dreams of beauty)",148],
            ["Flood",149],
            ["All My Wildest Dreams",150],
            ["Dorm Mates",151],
            ["The 69",152],
            ["Falling Towards Something (It Might Just Be You)",153],
            ["A Love Story in Four Acts",154],
            ["The Intricacies of Magical Etiquette",155],
            ["HBG Mini-series: Lily",156],
            ["HBG Mini-series: Pureblood Wives",157],
            ["The Prewett Cup",158],
            ["An Odd Turn of Events",159],
            ["Night Moves",160],
            ["The Guest Bedroom",161],
            ["Mirrors And Opposites",162],
            ["The List",163],
            ["Friends & Lovers",164],
            ["The Boy Who Wanted Her",165],
            ["The Boy Who Was Hers",166],
            ["How We Live",167],
            ["The Infernal Plan",168],
            ["Center of Attention",169],
            ["Vein of Gold",170],
            ["Encounters After the Yule Ball",171],
            ["Love You Completely",172],
            ["A Chance Meeting",173],
            ["You're my what?",174],
            ["Not On His List",175],
            ["An Unexpected Source of Wisdom",176],
            ["Troika",177],
            ["Subservient Housewives and other Mythical Creatures",178],
            ["Ice Princess",179],
            ["Harry in a new world",180],
            ["Harry Potter and the Marriage Contracts",181],
            ["Live! For God's Sake, Live!",182],
            ["A Lesson in Propriety",183],
            ["Confessions Under A Night Sky",184],
            ["The Weasley Wives' Club",185],
            ["A Place To Call Home",186],
            ["Unsealed",187],
            ["Slumber Party",188],
            ["A Memorable Farewell",189],
            ["Yearning Hearts",190],
            ["Open to Love",191],
            ["Things to Do in Berlin (When You're Bored)",192],
            ["Normal Things",193],
            ["The Girl Who Topped",194],
            ["Sort of Friends and Lovers",195],
            ["Various Climaxes",196],
            ["Luna's Desires",197],
            ["The Art of Being Slytherin",198],
            ["Welcome to the Family",199],
            ["Open Doors",200],
            ["One in a Million",201],
            ["You've Got Me Pegged",202],
            ["Let go",203],
            ["Best Behaviour",204],
            ["The World's a Stage",205],
            ["(Revel)ations",206],
            ["Blood and Bones",207],
            ["Helping Hands",208],
            ["Cosmopolitan",209],
            ["My Mind Is Screaming (But Your Touch Brings Me Silence)",210],
            ["Paramount ~ Extension",211],
            ["We Three Seekers",212],
            ["Best Friends, Always",213],
            ["Harry Potter and The Heir of House Greengrass",214],
            ["From Southampton to New York and Beyond",215],
            ["Memorial Week",216],
            ["Rose's Birthday Present",217],
            ["Daphne Greengrass and the Importance Of Intent",218],
            ["The Importance Of Intent: After The Credits",219],
            ["On A Night Like This - Potter Chronicle's",220],
            ["May It Be \u2013 Potter Chronicles",221],
            ["Hounds & Hippogriffs - The Potter Chronicles",222],
            ["Embers of Ruin - The Potter Chronicles",223],
            ["The Role Reversal",224],
            ["Sensations Of Shemales: Items Of Aphrodomina",225],
            ["Becoming Lord Black",226],
            ["Harry Potter: The True Wizards Way",227],
            ["Flower Power",228],
            ["The Life and Times of Edward Lupin (permanently discontinued)",229],
            ["The Bite Of Darkness",230],
            ["Homunculus to the Life",231],
            ["Community Board: Looking for Companionship",232],
            ["Always Read the Instructions",233],
            ["Harry Potter: After the Battle",234],
            ["Substitute My Coke for Gin",235],
            ["Red Right Hand",236],
            ["Negotiate",237],
            ["Where The Grass Is Greener",238],
            ["Apex Predator",239],
            ["Society Fair",240],
            ["Harry Potter and The Truth or Dare?",241],
            ["Panacea",242],
            ["Novocaine",243],
            ["A Long-Awaited Letter",244],
            ["Born As The Seventh Month Dies",245],
            ["Neither Can Live While The Other Survives",246],
            ["Those Who Have Thrice Defied Him",247],
            ["Power The Dark Lord Knows Not",248],
            ["The Two Brothers",249],
            ["Daphne Greengrass and the Preemptive Adulterer",250],
            ["Harry Potter: Life With A Single Futa Mother",251],
            ["Firewhiskeys & Happy Endings",252],
            ["Harry Potter: The Big Bukkake Bang",253],
            ["Fleur Delacour and the Secret of the Teardrop",254],
            ["His Last Curse",255],
            ["Enough of Both",256],
            ["Old Love",257],
            ["Awakening",258],
            ["Harry Potter and The Revival of The Phoenix",259],
            ["Snakes, Cats, and Ladders",260],
            ["The Veela's Captive",261],
            ["A Soft Place to Land",262],
            ["Nineteen Years Later...",263],
            ["Amour Et Officium",264],
            ["You Will Never Put Me Through That Again",265],
            ["Fleur De Lis",266],
            ["Desperate Times",267],
            ["Under the Starry Skies, the Greengrass Lies",268],
            ["Who Wouldn't Want You",269],
            ["It's Complicated",270],
            ["Pretty Please with a Ginny on Top",271],
            ["Four Times Harry Walked in on Ron and Hermione and One Time He Didn't",272],
            ["M\u00e9nage \u00e0 Quatre",273],
            ["Brumous",274],
            ["Needs",275],
            ["Her Goodbye",276],
            ["Bath and Bed",277],
            ["Homework with Hermione",278],
            ["Harry Potter and the Prefects Bath",279],
            ["Library Princess",280],
            ["Emerald Coven",281],
            ["Dirty games",282],
            ["The Courtesan",283],
            ["Enjoy the Fireworks",284],
            ["Feral",285],
            ["Domesticated",286],
            ["Godfather Neville",287],
            ["Voyeurism is such a strong word",288],
            ["Reciprocation is key",289],
            ["Tell Me Your Secrets",290],
            ["Black Ivy",291],
            ["Bolts from the Blue!",292],
            ["Something New",293],
            ["Hot Massage",294],
            ["What are we celebrating?",295],
            ["Lines of Life",296],
            ["Stockings Required",297],
            ["For The First Time",298],
            ["Susan Potter nee Bones",299],
            ["Chivalry",300],
            ["The Anniversary",301],
            ["A Very Potter Christmas",302],
            ["Thrall or not Thrall, that Is the Question",303],
            ["Royal Ward",304],
            ["A Dream to Remember",305],
            ["Desires and Delusions",306],
            ["Just One Night",307],
            ["Negligentia",308],
            ["Sleepless Nights",309],
            ["Shifting towards Eachother",310],
            ["Returning to the Start",311],
            ["After the Chamber - Lords and Ladies",312],
            ["Days to Come",313],
            ["The Secret Truth",314],
            ["Simplicity",315],
            ["Everything will be ok in the end",316],
            ["Interludes and Vignettes",317],
            ["Trials of The Stone",318],
            ["Spring Equinox",319],
            ["Sympathetic Properties",320],
            ["Give Me Love",321],
            ["Bad Timing",322],
            ["Hermione's Little Whore",323],
            ["Remember My Name",324],
            ["La maladie du baiser",325],
            ["Luna Joins the Fun",326],
            ["That Certain Something",327],
            ["Microclimat sentimental",328],
            ["A Very Fast Learner",329],
            ["Herbal Tea",330],
            ["Harry the Playboy",331],
            ["Hollow",332],
            ["Harry Potter and the Best Man's Job",333],
            ["Always",334],
            ["Dessert",335],
            ["Cheat on me",336],
            ["Le Coup de Foudre est de couleur Rouge Carmin",337],
            ["A Cadmean Victory",338],
            ["Reunion",339],
            ["A Family Relationship",340],
            ["A Bonding",341],
            ["46 Hours",342],
            ["Creating a Balance",343],
            ["Long Live The Queen",344],
            ["Breath of the Inferno",345],
            ["Sirius Black and the Raising of Children",346],
            ["Amicus Protectio Fortis",347],
            ["Forgotten Affairs",348],
            ["Dodging Prison and Stealing Witches - Revenge is Best Served Raw",349],
            ["Lily Potter and the Witches of Salem",350],
            ["Christmas Holiday",351],
            ["Fur and Feathers",352],
            ["Deck the Halls",353],
            ["Contractual Invalidation",354],
            ["Sweet seduction",355],
            ["More Than Equal",356],
            ["Tuesday Night",357],
            ["Purebloods and Their Tedious Traditions",358],
            ["Twisting Time",359],
            ["Love Multiplied",360],
            ["Gods Amongst Men",361],
            ["Changing Fate's Plans",362],
            ["Stay",363],
            ["Termination Without",364],
            ["To Reach Without",365],
            ["Harry Potter and the Rune Stone Path",366],
            ["Playdate",367],
            ["Amalgum \u2013 Lockhart's Folly",368],
            ["Gothic",369],
            ["Harry Potter and the Last Chance",370],
            ["When Fate Intervened",371],
            ["An Invisible Mishap",372],
            ["Harry Potter: Air Elemental",373],
            ["The Prefect's Bathroom",374],
            ["Love Under the Invisibility Cloak",375],
            ["A Feral Snake",376],
            ["Witch 3",377],
            ["The Power of the Potters",378],
            ["Happy Birthday Harry",379],
            ["Magical Puberty",380],
            ["Spellwork",381],
            ["Honour Thy Blood",382],
            ["Celebration",383],
            ["The Closer You Look",384],
            ["The Law",385],
            ["Heroes Assemble!",386],
            ["As Ron Likes It",387],
            ["Late Night Revelations",388],
            ["Soul Scars",389],
            ["One lucky Wife",390],
            ["Courage with Fear",391],
            ["Cure for Nightmares",392],
            ["A Beautiful Lie",393],
            ["Harry Potter and The Old Friend",394],
            ["A Godfather's Promise",395],
            ["The Lonely Letters",396],
            ["Sling Shots",397],
            ["Unexpected Happiness",398],
            ["The Guardian",399],
            ["From Ruin",400],
            ["Watching and Waiting Reloaded",401],
            ["Only You",402],
            ["Save Me",403],
            ["Three little words",404],
            ["The Black Lord",405],
            ["Dragon Chronicles 1: Muggle-Raised Champion",406],
            ["Dragon Chronicles 2: Harry Potter, Dragon Whisperer",407],
            ["Dying Light",408],
            ["The Insurance Policy",409],
            ["Albus and Harry's World Trip",410],
            ["Beat Your Heart Out",411],
            ["A Crow From Afar",412],
            ["Head Start",413],
            ["Green Light in the Dark",414],
            ["Cheating Death",415],
            ["If not for Umbridge",416],
            ["The Treasure Hunter",417],
            ["The Weasley Perspective",418],
            ["Power He Knows Not",419],
            ["The Boy Who Lived, The Brightest Witch and The Boy Who Wasn't",420],
            ["River Deep, Mountain High",421],
            ["Brontide",422],
            ["Need Protection?",423],
            ["Quidditch Tales",424],
            ["The Lust of Gryffindors",425],
            ["By the Moon Light",426],
            ["Better Than Cake",427],
            ["Shagging Psychology",428],
            ["Brothers",429],
            ["Castles",430],
            ["The Purpose of Wings",431],
            ["Through Shadows",432],
            ["Harry Potter: Thinking like a Thief",433],
            ["Gabrielle's Most Joyous No\u00ebl",434],
            ["Learning from Lily",435],
            ["Taken and Forgotten",436],
            ["Entombed",437],
            ["The Lost Year",438],
            ["A Different Type of Bond",439],
            ["A King's Path",440],
            ["Brothers: The Second Chapter",441],
            ["Your Arse Is Mine!",442],
            ["The Head Boy's Room",443],
            ["Reflection - Part of Averlovi's The Potter Chronicles",444],
            ["The Survivors",445],
            ["An Avenger's Anguish",446],
            ["Petrichor",447],
            ["Melting the Ice",448],
            ["Stars Glow, Shadows Fall",449],
            ["The Focus of a Healer",450],
            ["Moody's Blues",451],
            ["The Hogwarts Lonely Hearts Club",452],
            ["How Silently She Sings",453],
            ["Pray For The Wicked",454],
            ["Organic",455],
            ["To Catch A Killer",456],
            ["The Strange Case of Love",457],
            ["Fire and Ice",458],
            ["The Family that Chooses You",459],
            ["The Family that Heals",460],
            ["Extended Family",461],
            ["Fleur De Lis",462],
            ["The Winding Road",463],
            ["The Lion and The Lioness",464],
            ["Call Me Edward",465],
            ["A Dark Year",466],
            ["Kiss of Life",467],
            ["On The Hunt",468],
            ["Reading HP - 1",469],
            ["Agent Potter: The Wizard of WAND",470],
            ["Daphne Greengrass and the Boy Who Lived",471],
            ["The Delicate Art of Raising Thestrals",472],
            ["Harry Potter and the Ritual of Love's Memory",473],
            ["Written in the Stars",474],
            ["Contractual Obligation",475],
            ["Never Silence A Lion's Roar",476],
            ["The Lost Horcrux",477],
            ["A short life full of long years",478],
            ["Harry Evans: Memoirs of a well-lived Death (SI)",479],
            ["A Taste of Magic",480],
            ["Intrinsicality",481],
            ["We're Home",482],
            ["Hatal Fart Attack",483],
            ["Beautiful",484],
            ["Parce que",485],
            ["Back Again, Harry?",486],
            ["The Harmony Bond",487],
            ["The Obligatory Marriage Law Fic",488],
            ["Knowing Where to Look",489],
            ["Seduced by a Veela",490],
            ["Ron's Howler",491],
            ["The Unmentionables?",492],
            ["Delenda Est",493],
            ["Harry Potter and the Betrothal Contract",494],
            ["The Accidental Bond",495],
            ["Heart and Soul",496],
            ["Cold blood",497],
            ["The Return of the Marauders",498],
            ["To Become Whole Again",499],
            ["Fine Then!",500],
            ["It's My Life",501],
            ["BitterSweet Irony",502],
            ["Harry Potter After the War",503],
            ["A Different Halloween",504],
            ["Lucky Harry",505],
            ["How to Cage My Own Angel",506],
            ["For the Best",507],
            ["Death's Doorbell",508],
            ["Quoth the Raven, Nevermore",509],
            ["From The Ashes Of Magic",510],
            ["The Pureblood Princess",511],
            ["Harry Potter, Rise From Dust",512],
            ["On Teenagers And Love",513],
            ["For the Love of Ginny",514],
            ["She Who Holds the Strings",515],
            ["The Harry Potter Writers Circle",516],
            ["One Night",517],
            ["Nanny Wanted",518],
            ["A Set Up Gone Wrong",519],
            ["No Regrets",520],
            ["The Autumn Swan",521],
            ["Snake in the Chestnut",522],
            ["The Elusive Prince",523],
            ["A Call to Arms",524],
            ["Is this fate?",525],
            ["The Past Always Catches Up",526],
            ["Unatoned",527],
            ["Coach Granger",528],
            ["Never Let Me Go",529],
            ["No Thinking Thing",530],
            ["Passionate Interlude",531],
            ["Dance Your Heart Out",532],
            ["Plus One",533],
            ["A Quidditch pitch and five Galleons",534],
            ["A Roar and a Slither",535],
            ["Stregati",536],
            ["Addiction",537],
            ["Purple",538],
            ["Touch Me",539],
            ["The List",540],
            ["Potter's Angels",541],
            ["The Power of the Press",542],
            ["One-Ness",543],
            ["Wizards Fall",544],
            ["In the Library",545],
            ["The Box",546],
            ["Harry Potter and the Four Heirs",547],
            ["Intervention",548],
            ["Temptation",549],
            ["Working Late",550],
            ["For The First Time",551],
            ["The ShampooDragon Seduction",552],
            ["Discretion",553],
            ["Forgotten But Not Gone",554],
            ["Harry Potter and the Stress Relieving Breakfast",555],
            ["The Perils of Prospective Pregnancy",556],
            ["The Love of Your Life",557],
            ["The Witchunters of London",558],
            ["The Insta-Family Effect",559],
            ["The Secret Desire",560],
            ["Come Back and Haunt Me",561],
            ["Harry Potter and the Two Flowers",562],
            ["Alternative Rebirth",563],
            ["Harry Potter and the Nameless Man",564],
            ["Success!",565],
            ["Happy Birthday, Harry!",566],
            ["Following Instinct",567],
            ["Served Cold",568],
            ["Harry Potter and the 11th Commandment",569],
            ["Any Way You Want It",570],
            ["Harry's Veela",571],
            ["What Are Friends For?",572],
            ["The Benefits",573],
            ["Mine",574],
            ["Four Champions",575],
            ["Burning Love",576],
            ["Harry, Hermione and Lily",577],
            ["Unexpected",578],
            ["Heirs of the Founders",579],
            ["Charlie's Child",580],
            ["What We're Fighting For",581],
            ["A Pleasurable Jealousy",582],
            ["The Legacy",583],
            ["Welcome to Burlesque",584],
            ["Muggleborn Teacher",585],
            ["I told him, Gaby I told him that I loved you",586],
            ["Christmas FemSlash Special",587],
            ["How it all started",588],
            ["The Second Time Around",589],
            ["Baby, It's Cold Outside",590],
            ["Seasons of Change",591],
            ["You and I Collide",592],
            ["A Very Merry Christmas Indeed",593],
            ["Check... and Mate",594],
            ["That Which Matters Most",595],
            ["Moving On",596],
            ["Innocence Asunder",597],
            ["Sharing",598],
            ["Tomorrow",599],
            ["What Miranda Wants",600],
            ["I Hate It When She Does That",601],
            ["Asari Nights",602],
            ["Doctor's Prescription",603],
            ["Life's a Catch",604],
            ["The Perfect Pet",605],
            ["Saving Nezzy",606],
            ["Saving Sanity",607],
            ["Samantha's New Game",608],
            ["The Apology",609],
            ["Personal Growth",610],
            ["This Body Is Yours",611],
            ["Piano e Forte",612],
            ["Mass Effect: End of Days",613],
            ["Mass Effect: The Paths We Take (Discontinued)",614],
            ["Breaking Point",615],
            ["Of Heartache and Second Chances",616],
            ["Justified Means",617],
            ["Project Delta",618],
            ["The Short Road Home",619],
            ["The Anti-Agathics War",620],
            ["Uncommon Bonds",621],
            ["Seduction Theory",622],
            ["From Ashes",623],
            ["Better Angels: A Call to Arms",624],
            ["Catch",625],
            ["Branded",626],
            ["Mistress Nana",627],
            ["Exhilaration",628],
            ["Eat You Up",629],
            ["Wherein Ino Yamanaka Regales Sakura Haruno With Her Long List of Conquests",630],
            ["Honeymooners",631],
            ["Mother\/Daughter Love: Sequel One",632],
            ["Mother\/Daughter Love",633],
            ["Friends with Benefits",634],
            ["A Birthday Surprise",635],
            ["Waterfall of Love",636],
            ["Warped",637],
            ["Silver and Gold",638],
            ["Moonlight Sonata Antarctica",639],
            ["Follow The Leader",640],
            ["One Day in December",641],
            ["Accounts of Perversion and Obscenity",642],
            ["I Am NOT Going Through Puberty Again!",643],
            ["Naruto's Date",644],
            ["Boys And Their Toys",645],
            ["Safe and sound",646],
            ["A Few Extra Minutes",647],
            ["Just Like the Folks: The Orange Hokage and the Pink Medical Kunoichi",648],
            ["Just Like the Folks: The Orange Hokage and the Violet Flower",649],
            ["Just Like the Folks: The Orange Hokage and the Red Flute Player",650],
            ["Just Like the Folks: The Orange Hokage and the Purple Snake",651],
            ["Just Like the Folks: The Orange Hokage and the Yellow Sand Sickle",652],
            ["Just Like the Folks: The Orange Fox and the Maroon Vixen",653],
            ["Just Like the Folks: The Orange Fox and the Golden Firefly",654],
            ["Just Like the Folks: The Orange Fox and the Mint Beetle",655],
            ["Just Like the Folks: The Orange Hokage and the Russet Doctor",656],
            ["Just Like the Folks: The Orange Fox and the Brown Hound",657],
            ["Just Like the Folks: The Orange Hokage and the Lavender Byakugan Hime",658],
            ["Just Like the Folks: The Orange Fox and the Blue Origami Angel",659],
            ["Just Like the Folks: The Orange Hokage and the Auburn Mizukage",660],
            ["Just Like the Folks: The Orange Fox and the Black Nadeshiko Warrior",661],
            ["Just Like the Folks: The Orange Fox and the Crimson Healer",662],
            ["Just Like the Folks: The Orange Fox and the Glacial Princess",663],
            ["Just Like the Folks: The Orange Fox and the Carmine Queen",664],
            ["Just Like the Folks: The Orange Fox and the Jasmine Legendary Sucker",665],
            ["Just Like the Folks: The Orange Fox and the Chestnut Weapons Minx",666],
            ["Just Like the Folks: The Orange Fox and the Chocolate Strawberry",667],
            ["A Seductress In Red",668],
            ["New Rules",669],
            ["Kitsune's Seduction",670],
            ["A False Assumption",671],
            ["Unplanned",672],
            ["Counterpoise",673],
            ["Snake and Toad",674],
            ["Pervy Futa Party Games",675],
            ["Completely Ruined",676],
            ["Us Into Pieces.",677],
            ["Artwork",678],
            ["Demon's Dirty Dreams",679],
            ["The Secret Technique",680],
            ["Saturday Night",681],
            ["Family Secrets",682],
            ["She Made Him Wait",683],
            ["Cuckolding Konoha",684],
            ["Trouble In Paradise",685],
            ["Sakura's Plan",686],
            ["Feeling Her",687],
            ["I Kissed A Girl",688],
            ["Hinata, It can't be helped!",689],
            ["Hands Tied",690],
            ["Dorks.",691],
            ["Kage Sexbomb",692],
            ["Naruto the Kunoichi Toy",693],
            ["Sarada's Suprise",694],
            ["The Conquering Hero",695],
            ["Hinata's Little Bitch Boy",696],
            ["Shota CRA",697],
            ["A Man's Responsibility",698],
            ["A Woman's Touch",699],
            ["Pathos of the Shinobi",700],
            ["Hidden From Sunlight",701],
            ["The Last Prayer",702],
            ["Fun With Clones",703],
            ["Home is where my team is",704],
            ["Life Without Kurama",705],
            ["Unusual Lesson",706],
            ["Chasing You",707],
            ["Blood does not make a Family",708],
            ["Hinata's Plan",709],
            ["Post-War Passions",710],
            ["Chicken Ramen for the Pervert's Soul",711],
            ["Icha Icha Starlet",712],
            ["Invisible Favors",713],
            ["The Best for Us",714],
            ["Seasons of Life",715],
            ["Vacation",716],
            ["Blondes in Bed: The Leaf and The Cloud",717],
            ["Blondes in Bed: The Yellow Flash and The Golden Goddess",718],
            ["Blondes in Bed: The Leaf and The Firefly Heiress",719],
            ["Blondes in Bed: Two Leaves",720],
            ["Blondes in Bed: The Leaf and The Sand",721],
            ["Blondes in Bed: The Fox and The Cat",722],
            ["Blondes in Bed: The Leaf and Two Clouds",723],
            ["Blondes in Bed: Two Leaves and The Sand",724],
            ["Blondes in Bed: The Leaf, The Cloud, and The Firefly",725],
            ["Blondes in Bed: The Leaf and The Heavenly Harem",726],
            ["Lunch Break",727],
            ["Window Shopping",728],
            ["Hinata of the White Lotus",729],
            ["The Eternal Torment of Tayuya Uzumaki",730],
            ["Uzumaki Family Values",731],
            ["Naruto and Anko",732],
            ["Master of Jiongu",733],
            ["The Ninth Demon Lord: A Naruto Story",734],
            ["Naughty Naruto",735],
            ["Red",736],
            ["Tone And Stroke",737],
            ["Uzumaki Naruko: To the Victor, the Spoils V2",738],
            ["Futanari action in the Woods",739],
            ["Futas' boy Naruto",740],
            ["Transcending",741],
            ["Our Bond",742],
            ["Meet the Hyuga",743],
            ["More than enough (M-Rated version)",744],
            ["Life is Good",745],
            ["Naruto & Hinata Harem Hunters",746],
            ["Kinky Konoha",747],
            ["Rub it Out",748],
            ["Naruto's Weakness",749],
            ["Love Me Right",750],
            ["Treatments for Ecstasy",751],
            ["Diary of a White-Eyed Girl",752],
            ["Memories Of Others",753],
            ["In Charge",754],
            ["Fun at Resort",755],
            ["Naruto's Birthday Treat",756],
            ["Birthday",757],
            ["Particles of Dust",758],
            ["The Hormone",759],
            ["By Your Side (One Shot)",760],
            ["Mom's Disappointment, Son's Enjoyment",761],
            ["Seducing Naruto",762],
            ["Love In Bloom",763],
            ["Sister's Always Share REUPLOADED",764],
            ["A Loving Massage",765],
            ["Naruto: Re",766],
            ["Ino's Revenge on Sakura",767],
            ["The Tale of Gallant Naruto",768],
            ["Come In From The Rain",769],
            ["Shower Fun",770],
            ["If I Could Do It Over",771],
            ["Family Time",772],
            ["My Dear Weapons Mistress",773],
            ["The Yajuu Sannin",774],
            ["Friendly Advice",775],
            ["Birthday Gift",776],
            ["Sister in law, to sister in love!",777],
            ["Sense of Duty",778],
            ["New Things",779],
            ["Lemonade",780],
            ["Within Interest",781],
            ["Thunder Clap",782],
            ["The Caged Bird",783],
            ["Home with the Uzumakis",784],
            ["What happens in secret",785],
            ["Naruto Uzumaki Ero-Ninja",786],
            ["Addict",787],
            ["Secrets of the Gentle Fist(ing)",788],
            ["Sensei-kun",789],
            ["Naruto Shippuden: Inner Hinata",790],
            ["The Ripe Habanero",791],
            ["Yesterday Morning",792],
            ["Ninth",793],
            ["Harmless Attraction",794],
            ["Unusual Lessons",795],
            ["Journal of Hope",796],
            ["Always the quiet one",797],
            ["The Jinchuuriki's Brother",798],
            ["A Single Effect",799],
            ["Love Is Not A Cage",800],
            ["Red Thread",801],
            ["A Better Beginning",802],
            ["Of Scrolls and Chains",803],
            ["Legion of Naruto",804],
            ["Naruto Femdom Stories",805],
            ["Orange Spark",806],
            ["Secrets and smiles",807],
            ["The Cycle of Hatred: A Naruto Insert",808],
            ["The Sage Who Leapt Through Time",809],
            ["The Demon Shinobi of Konoha",810],
            ["In Her Bed",811],
            ["SugarSugar",812],
            ["Steam and Sweat",813],
            ["Memories",814],
            ["Instrumental",815],
            ["In The Heat of The Moment",816],
            ["Forgotten Prisoner",817],
            ["Naruto's Valentine Day",818],
            ["A Lucky Night of Love",819],
            ["Fatal Attraction",820],
            ["Drifting",821],
            ["Opportunities",822],
            ["The Impossible Car Dream",823],
            ["And Time Again",824],
            ["No Oath, No Spell",825],
            ["The Orange Bedroom",826],
            ["Want Verus Need",827],
            ["Sexually Frustrated",828],
            ["Eternal Love",829],
            ["Anko's Roses",830],
            ["The Ties that Bind Us: A Naruto and Kushina Love Story",831],
            ["Kings of Foreplay",832],
            ["Naruto Orange Typhoon",833],
            ["Willingly Snared in the Widow's Web",834],
            ["When One Domino Falls",835],
            ["Moving On",836],
            ["En'leass*",837],
            ["Yours Truly",838],
            ["Like a Damn Princess",839],
            ["The Wager",840],
            ["Novigrad: An Interlude",841],
            ["Too Good to Last",842],
            ["Blonde",843],
            ["A Cure for All Ills",844],
            ["Thoughts To A Friend",845],
            ["Wedding Day",846],
            ["Do computers dream of electric armu?",847],
            ["The Empress' Child",848],
            ["The Other Woman",849],
            ["From Beyond the Sky",850],
            ["A Life Entwined",851],
            ["Afterlife",852],
            ["Xenoblade Chronicles 2: Afterstories",853],
            ["Xenoblade Chronicles 2: Atonement",854],
            ["Shadows of Alrest",855],
            ["A Place Called Home",856],
            ["Love in Low Orbit",857],
            ["The Temptation of Rex",858],
            ["Fire Tempered",859],
            ["An Eternal History",860],
            ["Aegis Dish",861],
            ["A King Amongst Paupers",862],
            ["Lost in Orbit",863],
            ["The One Where Nia (Eventually) Gets Something Nice",864],
            ["Useful",865],
            ["Titan Eater",866],
            ["More Than Just a Memory",867],
            ["Trinity: Awaken. Reconcile. Resurge.",868],
            ["A Visit",869],
            ["The Soldier and the Thespian",870],
            ["I Need a Healer",871],
            ["Nia telling her secret to Rex early",872],
            ["All Three Of Them",873],
            ["New Frontier",874],
            ["The New World",875],
            ["The Heros Return",876],
            ["Settling In",877],
            ["Beach!",878],
            ["Moving In",879],
            ["Let's Go for a Ride",880],
            ["I Will Always Be By Your Side",881],
            ["Popcorn!",882],
            ["Family",883],
            ["Where we came from",884],
            ["The House That Rex Built",885],
            ["They Talked Later",886],
            ["Wake to See Your True Emancipation",887],
            ["All of the Above",888],
            ["Her War",889],
            ["You're The Greatest Gift I Could Ask For",890],
            ["Lovemaking with a Leftherian",891],
            ["Nia's Sundress Is Too Distracting!",892],
            ["The Early Morning Ramble",893],
            ["Mistress and Pet",894],
            ["Where We Belong",895],
            ["Teaching Them a Thing or Three",896],
            ["Masterpiece",897],
            ["Shard of the Aegis (Future Reborn)",898],
            ["Revising the Script",899],
            ["Cloudclear Candy",900],
            ["Father Figure",901],
            ["The Hidden Shield",902],
            ["Returning the Favor",903],
            ["Off-Seers Need a Good Laugh Too",904],
            ["Melt",905],
            ["Forever After",906],
            ["Dreams",907],
            ["Do I Remember You?",908],
            ["A step away",909],
            ["His Mio",910],
            ["Write it down or you'll forget",911],
            ["Knowledge obtained",912],
            ["Sunk Cost Fallacy",913],
            ["There is a handful of courage in my heart",914],
            ["Deathly loneliness attacks",915],
            ["Risk negation",916],
            ["Quick to their ends our candles burn until we're free",917],
            ["Two souls once lost",918],
            ["Eleven, eleven",919],
            ["Who, me?",920],
            ["'Til We Find Ourselves, Again",921],
            ["Reunited",922],
            ["A Bonding of Two",923],
            ["Know thy enemy",924],
            ["Memories of what we could have been",925],
            ["Sundancer",926],
            ["A lot can happen between now and never",927],
            ["How they used to Love",928],
            ["Just a Night In Camp",929],
            ["Where We Don't Belong",930],
            ["Our Hopes and Dreams",931],
            ["For Want of a Dry Wing",932],
            ["The Clock Strikes Six",933],
            ["A Quiet, Empty Moment",934],
            ["The Queen's Orders",935],
            ["From the Cradle to the Grave (and back again)",936],
            ["Her Mimi",937],
            ["And eat it too",938],
            ["What Comes Next",939],
            ["You Got Any Babies?",940],
            ["Our Feelings Will Never Change",941],
            ["Reimagination",942],
            ["Whatever It Is, With You",943],
            ["Long or Short",944],
            ["I am the only lonely casualty",945],
            ["A Promise of Morning Dew",946],
            ["A Place To Be Alive",947],
            ["A Strange Feeling",948],
            ["It Was Right On The Tip Of My Tongue",949],
            ["Not Mine",950],
            ["Momentary Weakness",951],
            ["Resemblances",952],
            ["None, Then Three",953],
            ["The Talk",954],
            ["Fledglings",955],
            ["Endless Strength",956],
            ["For my part this is all I need",957],
            ["This goodbye is not the end",958],
            ["Catching up for our past lives",959],
            ["Sleepy Time with Noah and Mio",960],
            ["Instruments of Rebirth",961],
            ["You're Here; That's More Than Enough",962],
            ["Duet",963],
            ["Forever Interlinked Futures",964],
            ["Sotto Voce",965],
            ["Hand in Hand",966],
            ["The Consequences of Indirect Kissing",967],
            ["May Our Voices Reach, In Time",968],
            ["Driver and (Artificial) Blade",969],
            ["Promises are meant to be kept",970],
            ["Noah and the Name Game",971],
            ["Ad Tertium \/ Upon the Third",972],
            ["Traitor in the Mirror",973],
            ["Miyabi In The Middle",974],
            ["Breaking the Miyabunnit",975],
            ["Mio's Guide to Child Birth",976],
            ["No Nut Noah-vember",977],
            ["A Bridge Between Worlds",978],
            ["Fast Travel to Flavour City",979],
            ["Healers' Fate",980],
            ["The Potato Eyes of Spudding Justice",981],
            ["Too Much Information",982],
            ["The simple rites of undead war-girls",983],
            ["New Moon [Hiatus]",984],
            ["The City and Alexandria",985],
            ["Letters To Our Son",986],
            ["In Another Life",987],
            ["Reunion",988],
            ["Tea Leaves and Fourtune Clovers",989],
            ["A chat between the Monado's Heir and Master Driver",990],
            ["Her Majesty's Masquerade",991],
            ["Walking Forward, Looking Back",992],
            ["A Mother's Love and a Queen's Regret",993],
            ["Mirror Mirror",994],
            ["For When The Dawn Comes Again",995],
            ["The Queen in the Memorial Hall",996],
            ["Show and Tell",997],
            ["Life goes on",998],
            ["The Father, The Son, and the Rubber Duck",999],
            ["Riki Is Bestest Grampypon!",1000],
            ["Remember We Were Partners in Crime",1001],
            ["Unforeseen Reunion",1002],
            ["Broken Gauntlet (SPOILERS FOR XC3FR)",1003],
            ["Aionios' Strongest!",1004],
            ["New Life",1005],
            ["New Feelings",1006],
            ["His Best Work's Done in the Bath",1007],
            ["Ciao Papa",1008],
            ["Melancholy Milton and Mythra",1009],
            ["Memories of a distant, near world",1010],
            ["Looking up from Beneath the Ripples",1011],
            ["Across time and space",1012],
            ["Birdsong",1013],
            ["Full of Beans",1014],
            ["Memories of the Stoutheart and the Queen",1015],
            ["And Those We've Left Behind",1016],
            ["Campfire Conversations",1017],
            ["Many Parts of One Identity",1018],
            ["We'll meet again",1019],
            ["Pangram",1020],
            ["Scavenger's Code, Number Eight",1021],
            ["Ye Shall Be As Gods",1022],
            ["The Scars We Carry",1023],
            ["Moments Before Midnight",1024],
            ["The rhapsodist",1025],
            ["The Origin Archive",1026],
            ["Love Me Like That",1027],
            ["1+1=1",1028],
            ["The Red Left Hand of Fate",1029],
            ["Aionios High 101",1030],
            ["Forever Interlinked: Futures Redeemed",1031],
            ["Hot and cold",1032],
            ["Hero Quest: The Sword Demon Of Agnus",1033],
            ["An Aegisborn in Aionios",1034],
            ["The Power Of a Demon",1035],
            ["Stronger Together",1036],
            ["Stasis",1037],
            ["Drifting soul",1038],
            ["The Beginning's End",1039],
            ["As Nature Intended?",1040],
            ["The N stands for \"Not having a good time\"",1041],
            ["Our Repentance",1042],
            ["Second Chances",1043],
            ["Tales of Interlinked Worlds",1044],
            ["Visions of Another",1045],
            ["Goldenrod",1046],
            ["Future Awaits",1047],
            ["Storms",1048],
            ["End's Journey",1049],
            ["First Chance",1050],
            ["The Gift of Unity",1051],
            ["Triad",1052],
            ["Romance Stories for the Half-Homs Girl",1053],
            ["Loving you is a losing game",1054],
            ["Memory Husks",1055],
            ["A Parent's Secret",1056],
            ["(Re)unions",1057],
            ["Xenoblade Chronicles 3: Hero Quest Counterbalance",1058],
            ["Patience",1059],
            ["Bluebird",1060]
        ];
    }
}
