<?php

declare(strict_types=1);

use PHPUnit\Framework\Attributes\DataProvider;

require_once __DIR__ . '/../../tests/api/ApiTestCase.php';

#[\PHPUnit\Framework\Attributes\CoversClass(\ApiClient::class)]
#[\PHPUnit\Framework\Attributes\CoversClass(className: \Relation::class)]
class RelationsTest extends ApiTestCase
{
    #[DataProvider('relationNamesProvider')]
    public function testRelationNames(string $expectedName, int $index): void
    {
        $relations = $this->fetchData('/relations.php');

        $this->assertArrayHasKey($index, $relations, "Relation type at index {$index} is missing");
        $this->assertEquals($expectedName, $relations[$index]->name, "Relation type name at index {$index} does not match");
    }

    public function testRelationsCount(): void
    {
        $relations = $this->fetchData('/relations.php');
        $this->assertCount(
            count(self::relationNamesProvider()),
            $relations,
            'The number of relations returned does not match the expected count'
        );
    }

    public static function relationNamesProvider(): array
    {
        return [
            ["Angelise Ikaruga Misurugi / Hilda Schlievogt / Tusk",0],
            ["Angelise Ikaruga Misurugi / Tusk",1],
            ["Aerith Gainsborough / Cloud Strife / Tifa Lockheart",2],
            ["Aerith Gainsborough / Zack Fair",3],
            ["Cloud Strife / Jessie / Tifa Lockheart",4],
            ["Cloud Strife / Tifa Lockheart",5],
            ["Auron / OC",6],
            ["Lulu / Wakka",7],
            ["Tidus / Yuna",8],
            ["Albus Severus Potter / Scorpius Malfoy",9],
            ["Harry Potter / Lily Evans Potter",10],
            ["Harry Potter",11],
            ["Alicia Spinnet / Angelina Johnson / George Weasley",12],
            ["Alicia Spinnet / Angelina Johnson / Harry Potter / Katie Bell",13],
            ["Alicia Spinnet / Angelina Johnson",14],
            ["Alicia Spinnet / George Weasley",15],
            ["Alicia Spinnet / Ginevra 'Ginny' Weasley",16],
            ["Alicia Spinnet / Harry Potter",17],
            ["Amelia Bones / Sirius Black",18],
            ["Andromeda Black Tonks / Bellatrix Black Lestrange / Harry Potter / Narcissa Black Malfoy",19],
            ["Angelina Johnson / Frederick 'Fred' Weasley",20],
            ["Angelina Johnson / George Weasley",21],
            ["Angelina Johnson / Ginevra 'Ginny' Weasley",22],
            ["Angelina Johnson / Harry Potter",23],
            ["Apolline Delacour / Harry Potter",24],
            ["Apolline Delacour / Hermione Granger",25],
            ["Arthur Weasley / Molly Weasley",26],
            ["Astoria Greengrass / Daphne Greengrass / Harry Potter",27],
            ["Astoria Greengrass / Draco Malfoy",28],
            ["Astoria Greengrass / Gabrielle Delacour",29],
            ["Astoria Greengrass / Harry Potter / Luna Lovegood",30],
            ["Astoria Greengrass / Harry Potter",31],
            ["Astoria Greengrass / Luna Lovegood",32],
            ["Astoria Greengrass / OFC / OFC / OFC / OFC / OFC",33],
            ["Astoria Greengrass / Pansy Parkinson",34],
            ["Astoria Greengrass / Romilda Vane",35],
            ["Bellatrix Black Lestrange / Harry Potter",36],
            ["Bellatrix Black Lestrange / Hermione Granger",37],
            ["Blaise Zabini / Draco Malfoy / Hermione Granger",38],
            ["Blaise Zabini / Draco Malfoy / Pansy Parkinson",39],
            ["Blaise Zabini / Draco Malfoy",40],
            ["Blaise Zabini / Ginevra 'Ginny' Weasley",41],
            ["Blaise Zabini / Narcissa Black Malfoy",42],
            ["Blaise Zabini / Pansy Parkinson",43],
            ["Blaise Zabini / Terry Boot",44],
            ["Blaise Zabini / Tracey Davis",45],
            ["Cedric Diggory / Cho Chang / Harry Potter",46],
            ["Cedric Diggory / Cho Chang",47],
            ["Cedric Diggory / Fleur Delacour",48],
            ["Cedric Diggory / Harry Potter",49],
            ["Charles 'Charlie' Weasley / Daphne Greengrass",50],
            ["Charles 'Charlie' Weasley / Hermione Granger",51],
            ["Charles 'Charlie' Weasley / OFC / OFC / OFC / OFC / OFC",52],
            ["Cho Chang / Hannah Abbott / Harry Potter / Hermione Granger",53],
            ["Cho Chang / Harry Potter / Su Li",54],
            ["Cho Chang / Harry Potter",55],
            ["Cho Chang / Hermione Granger",56],
            ["Cho Chang / Katie Bell",57],
            ["Cormac McLaggen / Lavender Brown / Parvati Patil",58],
            ["Daphne Greengrass / Draco Malfoy / Pansy Parkinson",59],
            ["Daphne Greengrass / Draco Malfoy",60],
            ["Daphne Greengrass / Fleur Delacour / Harry Potter / Penelope Clearwater",61],
            ["Fleur Delacour / Harry Potter / Susan Bones",62],
            ["Daphne Greengrass / Gabrielle Delacour / Harry Potter",63],
            ["Daphne Greengrass / Gabrielle Delacour",64],
            ["Daphne Greengrass / Ginevra 'Ginny' Weasley / Harry Potter / Hermione Granger",65],
            ["Daphne Greengrass / Harry Potter / Hermione Granger / Susan Bones",66],
            ["Daphne Greengrass / Harry Potter / Hermione Granger",67],
            ["Daphne Greengrass / Harry Potter / Padma Patil / Pansy Parkinson",68],
            ["Daphne Greengrass / Harry Potter / Pansy Parkinson",69],
            ["Daphne Greengrass / Harry Potter / Tracey Davis",70],
            ["Daphne Greengrass / Harry Potter",71],
            ["Daphne Greengrass / Hermione Granger",72],
            ["Daphne Greengrass / Luna Lovegood",73],
            ["Daphne Greengrass / Narcissa Black Malfoy",74],
            ["Daphne Greengrass / Neville Longbottom",75],
            ["Daphne Greengrass / Padma Patil",76],
            ["Daphne Greengrass / Pansy Parkinson / Tracey Davis",77],
            ["Daphne Greengrass / Pansy Parkinson",78],
            ["Daphne Greengrass / Susan Bones",79],
            ["Daphne Greengrass / Theodore Nott",80],
            ["Daphne Greengrass / Tracey Davis",81],
            ["Dean Thomas / Ginevra 'Ginny' Weasley",82],
            ["Dean Thomas",83],
            ["Draco Malfoy / Ginevra 'Ginny' Weasley / Harry Potter",84],
            ["Draco Malfoy / Ginevra 'Ginny' Weasley",85],
            ["Draco Malfoy / Harry Potter",86],
            ["Draco Malfoy / Hermione Granger",87],
            ["Draco Malfoy / Pansy Parkinson",88],
            ["Dudley Dursley / OFC / OFC / OFC / OFC / OFC",89],
            ["Dudley Dursley / Pansy Parkinson",90],
            ["Edward 'Teddy' Lupin / Victoire Weasley",91],
            ["Fleur Delacour / Gabrielle Delacour / Harry Potter",92],
            ["Fleur Delacour / Gabrielle Delacour",93],
            ["Fleur Delacour / Harry Potter / Hermione Granger / Nymphadora Tonks",94],
            ["Fleur Delacour / Harry Potter / Nymphadora Tonks",95],
            ["Fleur Delacour / Harry Potter / William 'Bill' Weasley",96],
            ["Fleur Delacour / Harry Potter",97],
            ["Fleur Delacour / Hermione Granger / Ronald 'Ron' Weasley",98],
            ["Fleur Delacour / Hermione Granger / William 'Bill' Weasley",99],
            ["Fleur Delacour / Hermione Granger",100],
            ["Fleur Delacour / Viktor Krum",101],
            ["Fleur Delacour / William 'Bill' Weasley",102],
            ["Flora Carrow / Harry Potter / Hestia Carrow",103],
            ["Gabrielle Delacour / Ginevra 'Ginny' Weasley / Harry Potter",104],
            ["Gabrielle Delacour / Ginevra 'Ginny' Weasley",105],
            ["Gabrielle Delacour / Harry Potter",106],
            ["Gabrielle Delacour / Hermione Granger",107],
            ["Ginevra 'Ginny' Weasley / Gwenog Jones",108],
            ["Ginevra 'Ginny' Weasley / Harry Potter / Hermione Granger / Katie Bell",109],
            ["Ginevra 'Ginny' Weasley / Harry Potter / Hermione Granger / Luna Lovegood",110],
            ["Ginevra 'Ginny' Weasley / Harry Potter / Hermione Granger / Ronald 'Ron' Weasley",111],
            ["Ginevra 'Ginny' Weasley / Harry Potter / Hermione Granger / Susan Bones",112],
            ["Ginevra 'Ginny' Weasley / Harry Potter / Hermione Granger",113],
            ["Ginevra 'Ginny' Weasley / Harry Potter / Katie Bell",114],
            ["Ginevra 'Ginny' Weasley / Harry Potter / Luna Lovegood / Neville Longbottom",115],
            ["Ginevra 'Ginny' Weasley / Harry Potter / Luna Lovegood / Nymphadora Tonks",116],
            ["Ginevra 'Ginny' Weasley / Harry Potter / Luna Lovegood",117],
            ["Ginevra 'Ginny' Weasley / Harry Potter / Narcissa Black Malfoy",118],
            ["Ginevra 'Ginny' Weasley / Harry Potter / Neville Longbottom",119],
            ["Ginevra 'Ginny' Weasley / Harry Potter / OFC / OFC / OFC / OFC / OFC",120],
            ["Ginevra 'Ginny' Weasley / Harry Potter / Parvati Patil",121],
            ["Ginevra 'Ginny' Weasley / Harry Potter",122],
            ["Ginevra 'Ginny' Weasley / Hermione Granger / Luna Lovegood",123],
            ["Ginevra 'Ginny' Weasley / Hermione Granger / Nymphadora Tonks",124],
            ["Ginevra 'Ginny' Weasley / Hermione Granger",125],
            ["Ginevra 'Ginny' Weasley / Katie Bell",126],
            ["Ginevra 'Ginny' Weasley / Lavender Brown",127],
            ["Ginevra 'Ginny' Weasley / Luna Lovegood",128],
            ["Ginevra 'Ginny' Weasley / Neville Longbottom",129],
            ["Ginevra 'Ginny' Weasley / OFC / OFC / OFC / OFC / OFC",130],
            ["Ginevra 'Ginny' Weasley / Pansy Parkinson",131],
            ["Ginevra 'Ginny' Weasley / Ronald 'Ron' Weasley",132],
            ["Ginevra 'Ginny' Weasley / Tracey Davis",133],
            ["Hannah Abbott / Harry Potter",134],
            ["Hannah Abbott / Neville Longbottom",135],
            ["Alicia Spinnet / Harry Potter",136],
            ["Harry Potter / Hermione Granger / Lavender Brown / Parvati Patil",137],
            ["Harry Potter / Hermione Granger / Lily Evans Potter",138],
            ["Harry Potter / Hermione Granger / Ronald 'Ron' Weasley",139],
            ["Harry Potter / Hermione Granger / Tracey Davis",140],
            ["Harry Potter / Hermione Granger",141],
            ["Harry Potter / Katie Bell",142],
            ["Harry Potter / Lavender Brown",143],
            ["Harry Potter / Lily Evans Potter",144],
            ["Harry Potter / Luna Lovegood",145],
            ["Harry Potter / Narcissa Black Malfoy",146],
            ["Harry Potter / Neville Longbottom",147],
            ["Harry Potter / Nymphadora Tonks",148],
            ["Harry Potter / OFC / OFC / OFC / OFC / OFC",149],
            ["Harry Potter / OMC / OMC / OMC",150],
            ["Harry Potter / Padma Patil / Parvati Patil",151],
            ["Harry Potter / Padma Patil",152],
            ["Harry Potter / Pansy Parkinson",153],
            ["Harry Potter / Parvati Patil",154],
            ["Harry Potter / Ronald 'Ron' Weasley",155],
            ["Harry Potter / Rose Weasley",156],
            ["Harry Potter / Su Li",157],
            ["Harry Potter / Susan Bones",158],
            ["Harry Potter / Tracey Davis",159],
            ["Hermione Granger / Katie Bell",160],
            ["Hermione Granger / Lavender Brown / Parvati Patil",161],
            ["Hermione Granger / Lavender Brown",162],
            ["Hermione Granger / Luna Lovegood",163],
            ["Hermione Granger / Narcissa Black Malfoy",164],
            ["Hermione Granger / Neville Longbottom",165],
            ["Hermione Granger / Padma Patil",166],
            ["Hermione Granger / Pansy Parkinson / Ronald 'Ron' Weasley",167],
            ["Hermione Granger / Pansy Parkinson",168],
            ["Hermione Granger / Parvati Patil",169],
            ["Hermione Granger / Ronald 'Ron' Weasley",170],
            ["Hermione Granger / Rose Weasley",171],
            ["Hermione Granger / Tracey Davis",172],
            ["Hermione Granger / Viktor Krum",173],
            ["James Potter / Lily Evans Potter",174],
            ["Katie Bell / Seamus Finnigan",175],
            ["Harry Potter / Lavender Brown",176],
            ["Lavender Brown / Neville Longbottom",177],
            ["Lavender Brown / Parvati Patil",178],
            ["Lavender Brown / Ronald 'Ron' Weasley",179],
            ["Lavender Brown / Seamus Finnigan",180],
            ["Lucius Malfoy / Narcissa Black Malfoy",181],
            ["Luna Lovegood / Neville Longbottom",182],
            ["Luna Lovegood / Severus Snape",183],
            ["Millicent Bulstrode / Tracey Davis",184],
            ["Neville Longbottom / OFC / OFC / OFC / OFC / OFC",185],
            ["Neville Longbottom / Pansy Parkinson",186],
            ["Neville Longbottom / Tracey Davis",187],
            ["Nymphadora Tonks / Remus Lupin / Sirius Black",188],
            ["Nymphadora Tonks / Remus Lupin",189],
            ["OFC / OFC / OFC / OFC / OFC / Ronald 'Ron' Weasley",190],
            ["Padma Patil / Pansy Parkinson",191],
            ["Pansy Parkinson / Romilda Vane",192],
            ["Pansy Parkinson / Ronald 'Ron' Weasley",193],
            ["Pansy Parkinson / Seamus Finnigan",194],
            ["Pansy Parkinson / Susan Bones",195],
            ["Ronald 'Ron' Weasley / Tracey Davis",196],
            ["Rose Weasley / Victoire Weasley",197],
            ["Marlene McKinnon / Sirius Black",198],
            ["OFC / OFC / OFC / OFC / OFC / Sirius Black",199],
            ["Theodore Nott / Tracey Davis",200],
            ["Ronald 'Ron' Weasley",201],
            ["Alucard / Seras Victoria",202],
            ["Integra Hellsing / Lily Evans Potter / Sirius Black",203],
            ["Aria T'Loak / Councilor Tevos",204],
            ["Ashley Williams",205],
            ["Ashley Williams / Sha'ira",206],
            ["Benezia T'Soni / Matriarch Aethyta",207],
            ["Councilor Tevos / Shepard (F)",208],
            ["EDI",209],
            ["Miranda Lawson",210],
            ["Shepard (F)",211],
            ["Liara T'Soni",212],
            ["Liara T'Soni / Shepard (F)",213],
            ["Miranda Lawson / OFC / OFC / OFC / OFC / OFC",214],
            ["Miranda Lawson",215],
            ["Miranda Lawson / Shepard (M)",216],
            ["Shepard (F)",217],
            ["Chigusa Nana / Sugimura Kaoru",218],
            ["Akimichi Choji / Karui",219],
            ["Amaru / Uzumaki Naruto",220],
            ["Fuka / Uzumaki Naruto",221],
            ["Fuu / Hyuuga Hinata / Tayuya / Uzumaki Naruto",222],
            ["Fuu / Hyuuga Hinata / Uzumaki Naruto",223],
            ["Fuu / Tayuya",224],
            ["Fuu / Uzumaki Naruto",225],
            ["Haruno Mebuki / Haruno Sakura",226],
            ["Haruno Mebuki / Uzumaki Naruto",227],
            ["Haruno Mebuki / Haruno Sakura / Uzumaki Naruto",228],
            ["Haruno Sakura / Uchiwa Sasuke / Uzumaki Naruto",229],
            ["Haruno Sakura / Tenten / Uzumaki Naruto",230],
            ["Haruno Sakura / Tenten",231],
            ["Haruno Sakura / Uchiwa Sasuke / Uzumaki Naruto",232],
            ["Haruno Sakura / Uchiwa Sasuke",233],
            ["Haruno Sakura / Uzumaki Naruko",234],
            ["Haruno Sakura / Uzumaki Naruto",235],
            ["Haruno Sakura / Yamanaka Ino",236],
            ["Haruno Sakura / Hatake Kakashi / Uchiwa Sasuke / Uzumaki Naruto",237],
            ["Hotaru / Nii Yugito / Sabaku no Temari / Samui / Shion / Uzumaki Naruto / Yamanaka Ino",238],
            ["Hotaru / Samui / Uzumaki Naruto",239],
            ["Hotaru / Uzumaki Naruto",240],
            ["Hyuuga Hanabi / Hyuuga Hinata / OFC / OFC / OFC / OFC / OFC / Uzumaki Naruto",241],
            ["Hyuuga Hanabi / Hyuuga Hinata / Uzumaki Naruto",242],
            ["Hyuuga Hanabi / Uzumaki Naruto",243],
            ["Hyuuga Hinata / Hyuuga Neji / Uzumaki Naruto",244],
            ["Hyuuga Hinata / Shion / Uzumaki Naruto",245],
            ["Hyuuga Hinata / Tayuya / Uzumaki Naruto / Yamanaka Ino",246],
            ["Hyuuga Hinata / Tenten / Uzumaki Naruko / Yamanaka Ino",247],
            ["Hyuuga Hinata / Uzumaki Naruko",248],
            ["Hyuuga Hinata / Uzumaki Naruto / Yamanaka Ino",249],
            ["Hyuuga Hinata / Uzumaki Naruto",250],
            ["Hyuuga Hinata / Yamanaka Ino",251],
            ["Hyuuga Neji / Tenten",252],
            ["Inuzuka Hana / Uzumaki Naruto",253],
            ["Inuzuka Kiba",254],
            ["Karin / Uzumaki Naruto",255],
            ["Karui / Uzumaki Naruto",256],
            ["Kazahana Koyuki | Fujikaze Yukie / Uzumaki Naruto",257],
            ["Killer Bee / Uzumaki Kushina",258],
            ["Konan / Uzumaki Naruto",259],
            ["Kurotsuchi / Uzumaki Naruto",260],
            ["Mabui / Uzumaki Naruto",261],
            ["Mitarashi Anko / Uzumaki Naruto",262],
            ["Namikaze Minato / Senju Tsunade",263],
            ["Namikaze Minato / Uzumaki Kushina",264],
            ["Nara Shikamaru / Sabaku no Temari / Yamanaka Ino",265],
            ["Nara Shikamaru / Sabaku no Temari",266],
            ["Nara Shikamaru / Yamanaka Ino",267],
            ["Nii Yugito / Samui / Uzumaki Naruto",268],
            ["Nii Yugito / Uzumaki Naruto",269],
            ["Queen Sara / Uzumaki Naruto",270],
            ["Sabaku no Temari / Tenten",271],
            ["Sabaku no Temari / Uzumaki Naruto / Yamanaka Ino",272],
            ["Sabaku no Temari / Uzumaki Naruto",273],
            ["Sai / Uzumaki Naruto",274],
            ["Sai / Yamanaka Ino",275],
            ["Samui / Uzumaki Naruto",276],
            ["Sarutobi Asuma / Yuuhi Kurenai",277],
            ["Senju Tsunade / Uzumaki Naruto",278],
            ["Shizuka / Uzumaki Naruto",279],
            ["Tayuya / Uzumaki Naruto",280],
            ["Tenten / Uzumaki Naruto",281],
            ["Tenten / Uzumaki Naruto",282],
            ["Terumi Mei / Uzumaki Kushina / Uzumaki Naruto / Yamanaka Ino",283],
            ["Terumi Mei / Uzumaki Naruto",284],
            ["Uchiwa Mikoto / Uzumaki Naruto",285],
            ["Uchiwa Sarada / Uzumaki Naruto",286],
            ["Uchiwa Sasuke / Uzumaki Naruto",287],
            ["Uzumaki Naruto",288],
            ["Uzumaki Naruto / Yamanaka Ino",289],
            ["Tracer | Lena Oxton / Widowmaker | Amelie Lacroix",290],
            ["James Raynor / Sarah Kerrigan",291],
            ["Magistrate / November 'Nova' Terra",292],
            ["Geralt z Rivii | Geralt of Rivia / Yennefer z Vengerbergu | Yennefer of Vengerberg",293],
            ["Alvis / Shulk",294],
            ["Carna | Sharla / Reyn",295],
            ["Dunban / Vanea",296],
            ["Fiorung | Fiora / Melia Ancient | Melia Antiqua / Shulk",297],
            ["Fiorung | Fiora / Shulk",298],
            ["Melia Ancient | Melia Antiqua / Talco | Tyrea",299],
            ["Hikari | Mythra / Homura | Pyra / Niyah | Nia / Rex",300],
            ["Hikari | Mythra / Homura | Pyra / Niyah | Nia",301],
            ["Hikari | Mythra / Homura | Pyra / Pneuma / Rex",302],
            ["Hikari | Mythra / Homura | Pyra / Rex",303],
            ["Hikari | Mythra / Rex",304],
            ["Hikari | Mythra / Rex",305],
            ["Homura | Pyra / Niyah | Nia",306],
            ["Homura | Pyra / Rex",307],
            ["KOS-MOS / Shiki | Adenine",308],
            ["Meleph | Mòrag Ladair / Satahiko | Mikhail",309],
            ["Metsu | Malos / Shin | Jin",310],
            ["Niyah | Nia / Rex",311],
            ["Ozychlyrus Brounev Tantal | Zeke von Genbu / Saika | Pandoria",312],
            ["Pneuma / Rex",313],
            ["A / Shulk",314],
            ["Ashera / Eunie",315],
            ["Eunie / Taion",316],
            ["Mashiro | Fiona",317],
            ["Isurugi | Isurd / Taion",318],
            ["Joran / Lanz",319],
            ["Joran / Miyabi",320],
            ["Joran / Noah",321],
            ["Lanz / Sena",322],
            ["Linka / Panacea",323],
            ["Mio / Noah",324],
            ["M(io) / N(oah)",325],
            ["Melia Ancient | Melia Antiqua / Niyah | Nia",326],
            ["Mio / Miyabi / Noah",327],
            ["Mio / Miyabi",328],
            ["Mio / Noah",329],
            ["Mio / Sena",330],
            ["Mio / Taion",331],
            ["Miyabi / Noah",332],
            ["Niina | Alexandria / Taion",333],
            ["Rex / Shulk",334]
        ];
    }
}
