# .github/actions/notify-discord/action.yml
name: "Notify Discord"
description: "Send Discord notification with status"
inputs:
  status:
    required: true
  commit:
    required: true
  sonar_url:
    required: true
  discord_webhook:
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        if [ "${{ inputs.status }}" = "success" ]; then
          COLOR=3066993
          MESSAGE="✅ FFB Webservices - Sonar Succeeded"
          IMAGE_URL="https://c.tenor.com/Ud36Rrav628AAAAC/tenor.gif"
        else
          COLOR=15158332
          MESSAGE="❌ Fanfictions Bookmark Webservices (API) Failed"
          IMAGE_URL="https://c.tenor.com/nsEfkzN30TIAAAAC/tenor.gif"
        fi
        PAYLOAD=$(cat <<EOF
        {
          "embeds": [{
            "title": "${MESSAGE}",
            "description": "**Workflow**: ${{ github.workflow }}\n**Repository**: ${{ github.repository }}\n**Branch**: ${{ github.ref }}\n**Commit**: [${{ inputs.commit }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})\n**SonarQube Analysis**: [View Results](${{ inputs.sonar_url }})",
            "color": ${COLOR},
            "image": {"url": "${IMAGE_URL}"},
            "timestamp": "$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          }]
        }
        EOF
        )
        curl -X POST -H "Content-Type: application/json" -d "$PAYLOAD" "${{ inputs.discord_webhook }}"
