USE ffb_main;
DROP TRIGGER IF EXISTS trg_authors_insert;
DROP TRIGGER IF EXISTS trg_characters_insert;
DROP TRIGGER IF EXISTS trg_fandoms_insert;
DROP TRIGGER IF EXISTS trg_fanfictions_insert;
DROP TRIGGER IF EXISTS trg_languages_insert;
DROP TRIGGER IF EXISTS trg_links_insert;
DROP TRIGGER IF EXISTS trg_relations_insert;
DROP TRIGGER IF EXISTS trg_series_insert;
DROP TRIGGER IF EXISTS trg_tags_insert;
DROP TRIGGER IF EXISTS trg_users_insert;

DROP TRIGGER IF EXISTS trg_authors_delete;
DROP TRIGGER IF EXISTS trg_characters_delete;
DROP TRIGGER IF EXISTS trg_fandoms_delete;
DROP TRIGGER IF EXISTS trg_fanfictions_delete;
DROP TRIGGER IF EXISTS trg_languages_delete;
DROP TRIGGER IF EXISTS trg_links_delete;
DROP TRIGGER IF EXISTS trg_relations_delete;
DROP TRIGGER IF EXISTS trg_series_delete;
DROP TRIGGER IF EXISTS trg_tags_delete;
DROP TRIGGER IF EXISTS trg_users_delete;

DROP TRIGGER IF EXISTS trg_authors_update;
DROP TRIGGER IF EXISTS trg_characters_update;
DROP TRIGGER IF EXISTS trg_fandoms_update;
DROP TRIGGER IF EXISTS trg_fanfictions_update;
DROP TRIGGER IF EXISTS trg_languages_update;
DROP TRIGGER IF EXISTS trg_links_update;
DROP TRIGGER IF EXISTS trg_relations_update;
DROP TRIGGER IF EXISTS trg_series_update;
DROP TRIGGER IF EXISTS trg_tags_update;
DROP TRIGGER IF EXISTS trg_users_update;
