DROP USER IF EXISTS 'ffb_guest'@'localhost';
CREATE USER IF NOT EXISTS 'ffb_guest'@'localhost' IDENTIFIED BY '';
GRANT SELECT (name, fandom) ON ffb_main . view_data_characters TO 'ffb_guest'@'localhost';
GRANT SELECT (name, author, rating, description, language, score, evaluation) ON ffb_main . view_data_crossovers TO 'ffb_guest'@'localhost';
GRANT SELECT (name, author, rating, description, language, score, evaluation) ON ffb_main . view_data_fanfictions TO 'ffb_guest'@'localhost';
GRANT SELECT (name, character_name) ON ffb_main . view_data_relations TO 'ffb_guest'@'localhost';
GRANT SELECT ON ffb_main . view_fanfictions_characters TO 'ffb_guest'@'localhost';
GRANT SELECT ON ffb_main . view_fanfictions_fandoms TO 'ffb_guest'@'localhost';
GRANT SELECT ON ffb_main . view_fanfictions_links TO 'ffb_guest'@'localhost';
GRANT SELECT ON ffb_main . view_fanfictions_relations TO 'ffb_guest'@'localhost';
GRANT SELECT ON ffb_main . view_fanfictions_tags TO 'ffb_guest'@'localhost';
GRANT SELECT ON ffb_main . view_series_authors TO 'ffb_guest'@'localhost';
GRANT SELECT ON ffb_main . view_series_characters TO 'ffb_guest'@'localhost';
GRANT SELECT ON ffb_main . view_series_fandoms TO 'ffb_guest'@'localhost';
GRANT SELECT ON ffb_main . view_series_fanfictions TO 'ffb_guest'@'localhost';
GRANT SELECT ON ffb_main . view_series_languages TO 'ffb_guest'@'localhost';
GRANT SELECT ON ffb_main . view_series_relations TO 'ffb_guest'@'localhost';
GRANT SELECT ON ffb_main . view_series_tags TO 'ffb_guest'@'localhost';
GRANT SELECT ON ffb_main . view_series_tags TO 'ffb_guest'@'localhost';
GRANT SELECT ON ffb_stats . * TO 'ffb_guest'@'localhost';

DROP USER IF EXISTS 'ffb_user'@'localhost';
CREATE USER IF NOT EXISTS 'ffb_user'@'localhost' IDENTIFIED BY 'password'; -- Change password by instance admin
GRANT UPDATE (score_id) ON ffb_main . fanfictions TO 'ffb_user'@'localhost';
GRANT UPDATE (evaluation) ON ffb_main . fanfictions TO 'ffb_user'@'localhost';
GRANT UPDATE (score_id) ON ffb_main . series TO 'ffb_user'@'localhost';
GRANT UPDATE (evaluation) ON ffb_main . series TO 'ffb_user'@'localhost';
GRANT SELECT ON ffb_main . * TO 'ffb_user'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE ON ffb_tests . * TO 'ffb_user'@'localhost';
GRANT SELECT ON ffb_stats . * TO 'ffb_admin'@'localhost';

DROP USER IF EXISTS 'ffb_admin'@'localhost';
CREATE USER IF NOT EXISTS 'ffb_admin'@'localhost' IDENTIFIED BY 'ffb_admingrants3privileges'; -- Change password by instance admin
GRANT SELECT ON ffb_main . actions TO 'ffb_admin'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE ON ffb_main . authors TO 'ffb_admin'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE ON ffb_main . characters TO 'ffb_admin'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE ON ffb_main . fandoms TO 'ffb_admin'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE ON ffb_main . fanfictions TO 'ffb_admin'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE ON ffb_main . fanfictions_characters TO 'ffb_admin'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE ON ffb_main . fanfictions_fandoms TO 'ffb_admin'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE ON ffb_main . fanfictions_relations TO 'ffb_admin'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE ON ffb_main . fanfictions_tags TO 'ffb_admin'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE ON ffb_main . languages TO 'ffb_admin'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE ON ffb_main . links TO 'ffb_admin'@'localhost';
GRANT SELECT ON ffb_main . ratings TO 'ffb_admin'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE ON ffb_main . relations TO 'ffb_admin'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE ON ffb_main . relations_characters TO 'ffb_admin'@'localhost';
GRANT SELECT ON ffb_main . scores TO 'ffb_admin'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE ON ffb_main . series TO 'ffb_admin'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE ON ffb_main . series_fanfictions TO 'ffb_admin'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE ON ffb_main . tags TO 'ffb_admin'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE ON ffb_main . tag_types TO 'ffb_admin'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE ON ffb_main . users TO 'ffb_admin'@'localhost';
GRANT SELECT, INSERT ON ffb_main . users_actions TO 'ffb_admin'@'localhost';
GRANT SELECT (name, fandom) ON ffb_main . view_data_characters TO 'ffb_guest'@'localhost';
GRANT SELECT (name, author, rating, description, language, score, evaluation) ON ffb_main . view_data_crossovers TO 'ffb_guest'@'localhost';
GRANT SELECT (name, author, rating, description, language, score, evaluation) ON ffb_main . view_data_fanfictions TO 'ffb_guest'@'localhost';
GRANT SELECT (name, character_name) ON ffb_main . view_data_relations TO 'ffb_guest'@'localhost';
GRANT SELECT ON ffb_main . view_fanfictions_characters TO 'ffb_guest'@'localhost';
GRANT SELECT ON ffb_main . view_fanfictions_fandoms TO 'ffb_guest'@'localhost';
GRANT SELECT ON ffb_main . view_fanfictions_links TO 'ffb_guest'@'localhost';
GRANT SELECT ON ffb_main . view_fanfictions_relations TO 'ffb_guest'@'localhost';
GRANT SELECT ON ffb_main . view_fanfictions_tags TO 'ffb_guest'@'localhost';
GRANT SELECT ON ffb_main . view_series_authors TO 'ffb_guest'@'localhost';
GRANT SELECT ON ffb_main . view_series_characters TO 'ffb_guest'@'localhost';
GRANT SELECT ON ffb_main . view_series_fandoms TO 'ffb_guest'@'localhost';
GRANT SELECT ON ffb_main . view_series_fanfictions TO 'ffb_guest'@'localhost';
GRANT SELECT ON ffb_main . view_series_languages TO 'ffb_guest'@'localhost';
GRANT SELECT ON ffb_main . view_series_relations TO 'ffb_guest'@'localhost';
GRANT SELECT ON ffb_main . view_series_tags TO 'ffb_guest'@'localhost';
GRANT SELECT ON ffb_main . view_series_tags TO 'ffb_guest'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE ON ffb_tests . * TO 'ffb_admin'@'localhost';
GRANT SELECT ON ffb_stats . * TO 'ffb_admin'@'localhost';